name: notebook-build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ericwcc/standardnotes-app
          ref: main
          path: standardnotes-app
      - run: yarn install
        working-directory: standardnotes-app
      - run: yarn run build:web
        working-directory: standardnotes-app
